- name: Set authorized keys to ubuntu user
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ keys }}"

- name: Set authorized keys to isucon user
  become: true
  become_user: isucon
  become_method: sudo
  ansible.posix.authorized_key:
    user: isucon
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ keys }}"
