- hosts: localhost
  tasks:
    - import_role:
        name: webapp
        tasks_from: build
- hosts: webapp
  remote_user: ubuntu
  tasks:
    - import_role:
        name: webapp
        tasks_from: deploy
